// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MovieeRecommandationnML.Model
{
    public class ModelInput
    {
        [ColumnName("user_id"), LoadColumn(0)]
        public float User_id { get; set; }


        [ColumnName("item_id"), LoadColumn(1)]
        public float İtem_id { get; set; }


        [ColumnName("rating"), LoadColumn(2)]
        public float Rating { get; set; }


        [ColumnName("timestamp"), LoadColumn(3)]
        public float Timestamp { get; set; }


        [ColumnName("title"), LoadColumn(4)]
        public string Title { get; set; }


    }
}
