// This file was auto-generated by ML.NET Model Builder. 

using System;
using MovieeRecommandationnML.Model;

namespace MovieeRecommandationnML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                User_id = 0F,
                İtem_id = 50F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");
            Console.WriteLine($"User_id: {sampleData.User_id}");
            Console.WriteLine($"İtem_id: {sampleData.İtem_id}");
            Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
